# Generated by Django 4.0.3 on 2022-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issiqxona', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
